# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beyond Scheme - web application development in Ruby, Elixir & Java
email: hello@beyondscheme.com
description: > # this means to ignore newlines until "baseurl:"
  We do Ruby on Rails, Elixir apps in Phoenix Framework, Java applications in Play! Framework & Spring MVC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beyondscheme.com" # the base hostname & protocol for your site
twitter_username: BeyondSchemeCom
github_username: BeyondScheme
blog_url: http://blog.beyondscheme.com
static_maps_key: AIzaSyDHFWEJjlBpNFCGXZFtnzm8JWcektYvPx0

# Build settings
markdown: kramdown
